FROM python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    pandas \
    matplotlib \
    sqlalchemy \
    psycopg2-binary

COPY visualize_weather.py .

CMD ["python", "visualize_weather.py"]


